name: continuous-url-ping

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch: {}     # allows manual run

concurrency:
  group: continuous-url-ping
  cancel-in-progress: true  # cancels previous run if still active

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python -m pip install requests
      - name: Run continuous loop
        run: python check.py
